### ISSUE TITLE
error {0}

### ISSUE THREAD

**Issue by newmesiss** [yasinkuyu/brackets-tools#14]
I get this error when creating a new file with html5 templat

a ocurrido un error al intentar abrir  el archivo /_brackets_3942120/sin titulo-5.html(erro  {0})

**Comment by yasinkuyu** [comment]
Hello,

Thank you for reporting the problem. I'll make the necessary arrangements for this.

**Comment by dvorapa** [comment]
The same here. Tested on Brackets 1.2 (Linux beta release)
![snimek obrazovky porizeny 2015-01-29 16 41 30](https://cloud.githubusercontent.com/assets/5113916/5960457/c7682682-a7d5-11e4-95e2-b2a7101a828b.png)

**Comment by yasinkuyu** [comment]
Error fixed. Please update 0.2.0
