### ISSUE TITLE
Feature Request - Invert Columns and Rows in HTML Table

### ISSUE THREAD

**Issue by X-Raym** [yasinkuyu/brackets-tools#18]
HI !
I just found your nice bracket extension ! There is some really interesting things with HTML :)

Maybe can you take a look to an action for Inverting Columns and Rows in HTML Table ?
I don't know how to write an extension for bracket,
but I find how it could be done in jquery here => http://jsfiddle.net/CsgK9/2/
Maybe can you take a look at this ?

It is an nice feature that I have never found in any code editor, and I think it fit very well in your extension :)

Thanks for listening, don't hesitate to tell me if you are not interested by this.

**Comment by yasinkuyu** [comment]
We can assess a different extension. In this regard I will make planning a blank time.

Thank you.
