### ISSUE TITLE
Divide 'Tools' menu into two columns

### ISSUE THREAD

**Issue by dvorapa** [yasinkuyu/brackets-tools#19]
`Tools` menu is becoming too long - what about to divide it into two `Tools` and `HTML` menus? I know, that there already is an issue with submenus, but maybe better would be this? Or not?

**Comment by yasinkuyu** [comment]
If the value of the proposal support the submenu too late...

https://trello.com/c/EwLGRkYe/541-native-submenus

**Comment by dvorapa** [comment]
It could be a temporary solution until they accept and provide submenus support API
