### ISSUE TITLE
How do you select all tags as illustrated in your Screencast?

### ISSUE THREAD

**Issue by gmaggio** [yasinkuyu/brackets-tools#22]
How do you make **instant selection of all the tags** as illustrated in your screencast, such as those `li`s?

![Image of Yaktocat](https://camo.githubusercontent.com/2c9dc2cf2c121ee7fc22ee45181c31eae5848e2a/687474703a2f2f6936302e74696e797069632e636f6d2f326630356530672e6a7067)

**Comment by yasinkuyu** [comment]
ALT + DRAG from mouse (CLICK + MOVE)
