### ISSUE TITLE
[Öneri] Navigasyon Menüsü İptal Etme Seçeneği

### ISSUE THREAD

**Issue by QuasarX** [yasinkuyu/brackets-tools#25]
Başlıkta da belirttiğim gibi navigasyon menüsüne (Sağ tık menüsü) eklenen özellikleri iptal etme seçeneği eklenirse güzel olur. Sağ tık menüsü haddinden fazla kalabalık oluyor. Ayrıca araçlar menüsünden rahatlıkla erişebiliyoruz. İlginize teşekkürler.

**Comment by yasinkuyu** [comment]
İyi fikir. Yakın zamanda yeni versiyona dahil edeceğim.
